export enum graphqlType {
  Notification = 'Notification',
  Organization = 'Organization',
  Quests = 'Quests',
  Signer = 'Signer',
  User = 'User',
  UserAccount = 'UserAccount',
  UserIdentity = 'UserIdentity',
  UserInvitation = 'UserInvitation',
  Wallet = 'Wallet',
  Contact = 'Contact',
  Proposal = 'Proposal',
  Promo = 'Promo',
  Message = 'Message',
  History = 'History',
  PendingTransaction = 'PendingTransaction',
  PendingMessage = 'PendingMessage',
  ContractPermission = 'ContractPermission',
  ContractPreferences = 'ContractPreferences',
  Bookmark = 'Bookmark',
  Rewards = 'rewards',
  CryptoPositions = 'CryptoPositions',
  EmptyTokenAccounts = 'EmptyTokenAccounts',
}
